if not set -qU fish_initialized; and test (uname) = 'Darwin'
  # Homebrew
  abbr -a brewc 'brew prune; and brew cleanup'
  abbr -a brewC 'brew prune; and brew cleanup -s'
  abbr -a brewe 'brew edit'
  abbr -a brewi 'brew install'
  abbr -a brewl 'brew leaves'
  abbr -a brewn 'brew info'
  abbr -a brewo 'brew outdated'
  abbr -a brewr 'brew reinstall'
  abbr -a brews 'brew search'
  abbr -a brewu 'brew update; and brew upgrade'
  abbr -a brewx 'brew uninstall'

  # Homebrew Cask
  abbr -a cask  'brew cask'
  abbr -a caskc 'brew prune; and brew cleanup'
  abbr -a caskC 'brew prune; and brew cleanup -s'
  abbr -a caske 'brew cask edit'
  abbr -a caski 'brew cask install'
  abbr -a caskl 'brew cask list'
  abbr -a caskn 'brew cask info'
  abbr -a casko 'brew cask outdated'
  abbr -a caskO 'brew cask outdated --greedy'
  abbr -a caskr 'brew cask reinstall'
  abbr -a casks 'brew search'
  abbr -a casku 'brew cask upgrade'
  abbr -a caskU 'brew cask upgrade --greedy'
  abbr -a caskx 'brew cask uninstall'
  abbr -a caskX 'brew cask zap'
end
