#!/usr/bin/env bash

# fresh: bundler for dotfiles
fresh freshshell/fresh bin/fresh --bin=~/.local/bin/fresh

# format-udf: format a block device (hard drive or flash drive) in UDF
fresh JElchison/format-udf format-udf.sh --bin=~/.local/bin/format-udf

# vi:ft=sh:
