#!/bin/sh

set -e

. lib/env.sh
. lib/logging.sh
. lib/registry.sh
. lib/utils.sh

section "System Packages"
case $(uname) in
  Linux)
    if command -v pacman >/dev/null; then
      BLD="autoconf automake bison ccache clang cmake fakeroot gcc make pkgconf"
      LIB="libyaml"
      USR="ctags elinks fish gdb git git-lfs htop jq lftp perl-file-mimeinfo mosh neofetch neovim shellcheck socat stow tig tmux unzip whois xdg-utils"

      INSTALLED=$(pacman -Qq)
    elif command -v yum >/dev/null; then
      BLD="automake bison ccache clang cmake gcc make pkgconfig"
      LIB="bzip2-devel gdbm-devel libffi-devel libuuid-devel libyaml-devel ncurses-devel openssl-devel readline-devel sqlite-devel zlib-devel"
      USR="ctags elinks fish gdb git git-lfs gnupg htop jq lftp bsdtar perl-File-MimeInfo mosh neofetch neovim ShellCheck socat stow tig tmux2u unzip whois xdg-utils"

      INSTALLED=$(rpm -qa --queryformat '%{name}\n')
    else
      error "Unsupported package manager."
    fi
    ;;
  Darwin)
    BLD="automake ccache cmake"
    LIB="gmp gdbm libffi libyaml openssl readline"
    USR="coreutils ctags curl fish gdb git git-lfs gnupg htop jq lftp mosh neofetch neovim pinentry-mac shellcheck socat stow task-spooler tmux unzip xz"

    INSTALLED=$(brew ls -1)
    ;;
  *)
    error "Unsupported operating system."
    ;;
esac
for pkg in $BLD $LIB $USR; do
  if ! echo "$INSTALLED" | grep -Fwq "$pkg"; then
    PKGS="${PKGS:+$PKGS }$pkg"
  fi
done
if [ -n "$PKGS" ]; then
  if [ -z "$SKIP_PKGS" ]; then
    case $(uname) in
      Linux)
        if command -v pacman >/dev/null; then
          info "Installing system packages with pacman..."
          sudo sh -c "pacman -Sy --noconfirm $PKGS"
        elif command -v yum >/dev/null; then
          info "Installing system packages with yum..."
          sudo sh -c "yum install -y $PKGS"
        fi
        ;;
      Darwin)
        info "Installing system packages with brew..."
        sh -c "brew install $PKGS"
        ;;
    esac
  else
    important "The following system packages are missing:"
    echo "$PKGS"
  fi
else
  info "All system packages are installed."
fi

section "Language Support"
for support in support/*.sh; do
  if ! echo "$SKIP_LANGUAGES" | grep -Fq "$(stem "$support")"; then
    # shellcheck source=/dev/null
    . "$support"
  fi
done

important "Done! Restart your shell!"
